In [81]:
!pip install pymdptoolbox

In [207]:
import mdptoolbox
import numpy as np
T = np.array([[[0.3, 0.7],[0.9, 0.1]],[[0.2, .8],[0.1, 0.9]]])

In [208]:
T

array([[[0.3, 0.7],
        [0.9, 0.1]],

       [[0.2, 0.8],
        [0.1, 0.9]]])

In [209]:
R = np.array([[5, 10], [-1, 2]])

### MDP OPERATION : Finite Horizon

In [226]:
err1=1
err2=1
i=1

In [234]:
while ((err1<0.2) and (err2<0.2)):
    ql = mdptoolbox.mdp.FiniteHorizon(transitions=T, reward=R, discount=0.5, N=i)
    ql.run()
    ql.V
    err1=ql.V[0][0]-ql.V[0][1]
    err2=ql.V[1][0]-ql.V[1][1]
    i=i+1

In [235]:
print(ql.V)
print('NUMBER OF PERIODS:',i)
print('BELLMAN EQUATION CONVERGE ERROR:',ql.V[0][0]-ql.V[0][1])
print('BELLMAN EQUATION CONVERGE ERROR:',ql.V[1][0]-ql.V[1][1])

[[13.37523    13.2672     13.058      12.62       11.8        10.
   0.        ]
 [ 5.22630375  5.121275    4.9035      4.49        3.6         2.
   0.        ]]
NUMBER OF PERIODS: 1
BELLMAN EQUATION CONVERGE ERROR: 0.1080299999999994
BELLMAN EQUATION CONVERGE ERROR: 0.10502875000000067


In [233]:
ql.policy

array([[1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1]])

In [230]:
err2

1

### MDP OPERATION : Value Iteration

In [167]:
ql = mdptoolbox.mdp.ValueIteration(T, R, 0.5)
ql.run()
ql.V

(13.2672, 5.121275)

In [168]:
ql.policy

(1, 0)

### MDP OPERATION : QLearning

In [169]:
np.random.seed(0)
ql = mdptoolbox.mdp.QLearning(T, R, 0.5)
ql.run()
ql.V

(13.511712967351645, 5.2090134629098745)

In [170]:
ql.Q

array([[ 8.97536754, 13.51171297],
       [ 5.20901346,  5.03864966]])

In [171]:
ql.policy

(1, 0)

### EXAMPLE

In [86]:
import mdptoolbox, mdptoolbox.example
#T, R = mdptoolbox.example.forest()

In [87]:
T

array([[[0.3, 0.7],
        [0.9, 0.1]],

       [[0.2, 0.8],
        [0.1, 0.9]]])

In [88]:
R

array([[ 5, 10],
       [-1,  2]])

In [89]:
fh = mdptoolbox.mdp.FiniteHorizon(transitions=T, reward=R, discount=0.5, N=5)
# fh = mdptoolbox.mdp.FiniteHorizon(T, R, 0.9, 5)
fh.run()

In [90]:
fh.V

array([[13.2672  , 13.058   , 12.62    , 11.8     , 10.      ,  0.      ],
       [ 5.121275,  4.9035  ,  4.49    ,  3.6     ,  2.      ,  0.      ]])

In [91]:
fh.policy

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1]])

In [92]:
R

array([[ 5, 10],
       [-1,  2]])